services:
  service-recipe:
    image: ghcr.io/brewing-stand/service-recipe:master  # Pulls image from GHCR
    container_name: 'Brewing-stand-Service-Recipe'
    restart: unless-stopped
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:8080"   # Maps host port 8080 to container port 8080
      - "8081:8081"   # Maps host port 8081 to container port 8081
    volumes:
      - ./app_data:/app/data   # Optional: Bind mount if you need to persist app data locally (adjust as needed)

