version: '3.8'

services:
  service-recipe:
    image: ghcr.io/brewing-stand/service-recipe:sha256-b6e57cc5a862000da2d1c563c25b50698b7fe059f87d8894fc1b64cbadc08732.sig  # Pulls your image from GHCR
    container_name: 'Brewing-stand-Service-Recipe'
    restart: unless-stopped
    networks:
      - brewing_net
      environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:8080"   # Maps host port 8080 to container port 8080
      - "8081:8081"   # Maps host port 8081 to container port 8081
    volumes:
      - ./app_data:/app/data   # Optional: Bind mount if you need to persist app data locally (adjust as needed)
    networks:
      - brewing-network

networks:
  brewing-network:
    driver: bridge
